### ISSUE TITLE
Volume is scaled a bit to late

### ISSUE THREAD

**Issue by P4sca1** [Marcuzz/MetroLoad#2]
When you join the server with this loading screen installed, the music volume will be 1 for about 1 second. After that second the volume is scaling to the number in the vonfig (eg. 0.1).
Is there any way to start the music after scaling?

**Comment by Marcuzz** [comment]
I'm not sure. There might be another way to scale music in HTML. I might look into it

**Comment by P4sca1** [comment]
That would be great! 
Is there any way that I can make something like a timer of 3 seconds before the music is actually starting?

**Comment by Marcuzz** [comment]
I found out. Replace line 93 in inc/javascript.php with this:

``` javascript
$(function () {
    setVolume();
});
```

**Comment by P4sca1** [comment]
That was really fast. Thanks! <3

**Comment by P4sca1** [comment]
Because my line numbers seem to be a bit different:

could you post the whole file? (im just got a bit confused)

**Comment by Marcuzz** [comment]
replace the line that was 

``` javascript
window.onload=setVolume;
```

with 

``` javascript
$(function () {
    setVolume();
});
```

**Comment by P4sca1** [comment]
Allright. Great Thanks for your quick help!
