### ISSUE TITLE
Insecure HTML?

### ISSUE THREAD

**Issue by P4sca1** [Marcuzz/MetroLoad#3]
What does this Errors mean? 
They are in my console right after joining a server with this loading screen installed.

[HTML] The page at https://DOMAIN/loading/ttt/?mapname=ttt_fastfood_a6&steamid=76561198152415776 ran insecure content from http://fonts.googleapis.com/css?family=Oswald|Open+Sans:400,300,600,700|Montserrat:400,700.

[HTML] The page at https://DOMAIN/loading/ttt/?mapname=ttt_fastfood_a6&steamid=76561198152415776 ran insecure content from http://fonts.googleapis.com/css?family=Oswald|Open+Sans:400,300,600,700|Montserrat:400,700.

[HTML] The page at https://DOMAIN/loading/ttt/?mapname=ttt_fastfood_a6&steamid=76561198152415776 displayed insecure content from http://fonts.gstatic.com/s/montserrat/v6/zhcz-_WihjSQC0oHJ9TCYBsxEYwM7FgeyaSgU71cLG0.woff.

[HTML] The page at https://DOMAIN/loading/ttt/?mapname=ttt_fastfood_a6&steamid=76561198152415776 displayed insecure content from http://fonts.gstatic.com/s/montserrat/v6/IQHow_FEYlDC4Gzy_m8fcgFhaRv2pGgT5Kf0An0s4MM.woff.

[HTML] The page at https://DOMAIN/loading/ttt/?mapname=ttt_fastfood_a6&steamid=76561198152415776 displayed insecure content from http://fonts.gstatic.com/s/opensans/v13/DXI1ORHCpsQm3Vp6mXoaTXhCUOGz7vYGh680lGh-uXM.woff.

[HTML] The page at https://DOMAIN/loading/ttt/?mapname=ttt_fastfood_a6&steamid=76561198152415776 displayed insecure content from http://fonts.gstatic.com/s/opensans/v13/cJZKeOuBrn4kERxqtaUH3T8E0i7KZn-EPnyo3HZu7kw.woff.

[HTML] The page at https://DOMAIN/loading/ttt/?mapname=ttt_fastfood_a6&steamid=76561198152415776 displayed insecure content from http://fonts.gstatic.com/s/opensans/v13/MTP_ySUJH_bn48VBG8sNSnhCUOGz7vYGh680lGh-uXM.woff.

[HTML] The page at https:/DOMAIN/loading/ttt/?mapname=ttt_fastfood_a6&steamid=76561198152415776 displayed insecure content from http://fonts.gstatic.com/s/opensans/v13/k3k702ZOKiLJc3WVjuplzHhCUOGz7vYGh680lGh-uXM.woff.

[HTML] The page at https://DOMAIN/loading/ttt/?mapname=ttt_fastfood_a6&steamid=76561198152415776 displayed insecure content from http://fonts.gstatic.com/s/oswald/v10/-g5pDUSRgvxvOl5u-a_WHw.woff.

[HTML] The page at https://DOMAIN/loading/ttt/?mapname=ttt_fastfood_a6&steamid=76561198152415776 displayed insecure content from http://image.www.gametracker.com/images/maps/160x120/garrysmod/ttt_fastfood_a6.jpg.

[HTML] Unsafe JavaScript attempt to access frame with URL https://DOMAIN/loading/ttt/?mapname=ttt_fastfood_a6&steamid=76561198152415776 from frame with URL https://www.youtube.com/embed/?rel=0&autoplay=1. Domains, protocols and ports must match.

**Comment by Marcuzz** [comment]
Line 14, index.php. Change:

``` html
<link href="http://fonts.googleapis.com/css?family=Oswald|Open+Sans:400,300,600,700|Montserrat:400,700" rel="stylesheet" type="text/css" />
```

to 

``` html
<link href="//fonts.googleapis.com/css?family=Oswald|Open+Sans:400,300,600,700|Montserrat:400,700" rel="stylesheet" type="text/css" />
```

I'm not sure about the Unsafe Javascript attempt with Youtube as it already is https

**Comment by P4sca1** [comment]
Really fast support, thanks! 
Going to buy the script on Scriptfodder within the next month, to support your work! :) 

One question, that you may can answer: Is there any way to center the boxes more to the middle of the screen?

**Comment by Marcuzz** [comment]
Uhm, in what kind of way? Less space inbetween them or?

**Comment by P4sca1** [comment]
I want to move all the boxes a bit more down. Currently they are more in the top of the screen but I want them to be more in the center. 
I tried to show you with this because my english is not that god: http://prntscr.com/7f3iwf

**Comment by Marcuzz** [comment]
in css/style.css at the complete top place this:

``` css
html, body {
    margin: 0;
    padding: 0;
    width: 100%;
    height: 100%;
    display: table;
}
```

and at the bottom this:

``` css
.wrapper {
    display: table-cell;
    vertical-align: middle;
}
```

and in index.php right below:

``` html
<body class="bg" ...>
```

place:

``` html
<div class="wrapper">
```

and then at the bottom of index.php above

``` html
</body>
```

simply put:

``` html
</div>
```

**Comment by P4sca1** [comment]
I' ll check tommorroe if this worked for me. Again, thanks for your great help! :)

**Comment by P4sca1** [comment]
Works great! :+1:
