### ISSUE TITLE
Cycling Backgrpunds scaled wrong

### ISSUE THREAD

**Issue by P4sca1** [Marcuzz/MetroLoad#5]
In here https://github.com/Marcuzz/MetroLoad/issues/3 you told me how to center the boxes etc. That really worked great, thanks for that!
Today I tried out the cycling background images, but because of the centering they are a bit crazy scaled; have a look here: 
http://prntscr.com/7i3ebb

**Comment by P4sca1** [comment]
Any news about this issue?

**Comment by Marcuzz** [comment]
Weird, quite busy atm I'll look into it soon

**Comment by P4sca1** [comment]
Yeah, I've just seen the new Prometheus Update. Great Work! 
Just tell me when you have time to look into it

**Comment by P4sca1** [comment]
Any news about this?

**Comment by Marcuzz** [comment]
http://mcz.pw/GcFD.png

move that block above the line which is directly above it like so:

http://mcz.pw/87ZT.png

**Comment by Marcuzz** [comment]
in index.php, sorry I forgot to mention the file lol

**Comment by P4sca1** [comment]
Great!
