### ISSUE TITLE
Badly Optimized or what?

### ISSUE THREAD

**Issue by ghost** [Marcuzz/MetroLoad#6]
Hello, I got a problem, after I installed the loadingscreen, it doesnt load, sometimes it gives 522, 504 and such, it once loaded, but that was it, the website itself loads within seconds.. you can try it here:

https://platincore.ml <-- default website, loading fine.

https://platincore.ml/loadingscreen/ <-- the loadingscreen, not running fine ;-;

Edit: Yup, it seems to be badly optimized? nginxs error.log said its a timeout, so I had to change

```
fastcgi_read_timeout 60; > fastcgi_read_timeout 150;
```

it then took like a minute to load, is there a way to make it better?

**Comment by Marcuzz** [comment]
Excuse me? You're the only one ever with this problem. If you're going to report something please include the php error log. Your host probably can't reach the Steam servers. There's absolutely nothing else that can cause a loading issue

**Comment by ghost** [comment]
Its also inside the browser for me, I dont know if its just at my end, or can you load it as usual, or is it slow for you too?

And what you mean with "Cant reach the steam servers", Since I can access other websites from me through ingame fine.

**Comment by Marcuzz** [comment]
It's fast for me

**Comment by ghost** [comment]
Well, I guess topic closed then, because I dont know why nginx gave me the timeouts.
